import {createFileRoute,Link} from '@tanstack/react-router';
import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {useServerFn} from '@tanstack/react-start';
import {Building2,Plus,UserPlus,ArrowRight,Trash2} from 'lucide-react';
import {toast} from 'sonner';
import {AppShell} from '@/components/AppShell';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {agencyAction,agencyData} from '@/lib/agency.functions';
import {AGENCY_PLANS,pageHead} from '@/lib/site';
import {formatDate,formatMoney,ROLE_LABELS} from '@/lib/nestfam';
import {useCases} from '@/hooks/useCases';
import {useAuth} from '@/hooks/useAuth';
export const Route=createFileRoute('/agency')({head:()=>pageHead('Agency workspace','Manage your agency, private professional circle, case invitations, tasks and subscription records.'),component:Agency});
function Agency(){
 const {user,refresh}=useAuth();const qc=useQueryClient();const load=useServerFn(agencyData);const act=useServerFn(agencyAction);
 const {data,error,isLoading}=useQuery({queryKey:['agency-workspace',user?.id],enabled:Boolean(user),queryFn:()=>load()});
 const {data:cases=[]}=useCases();const [agencyId,setAgencyId]=useState('');const agency=data?.agencies.find(a=>a.id===agencyId)??data?.agencies[0];
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [inviteRole,setInviteRole]=useState<'agency_staff'|'professional'|'clinic_staff'|'agency_admin'>('professional');
 const admin=data?.members.some(m=>m.agency_id===agency?.id&&m.user_id===user?.id&&m.role==='agency_admin');
 const mutation=useMutation({mutationFn:act,onSuccess:async()=>{setEmail('');setName('');await qc.invalidateQueries();await refresh();toast.success('Workspace updated');},onError:(e:Error)=>toast.error(e.message)});
 const scopedCases=cases.filter(c=>c.agency_id===agency?.id);const scopedMembers=data?.members.filter(m=>m.agency_id===agency?.id)??[];const scopedInvites=data?.invitations.filter(i=>i.agency_id===agency?.id)??[];
 return <AppShell title="Agency workspace" subtitle="Your relationships. Your team. Your private cases.">
 {error&&<p role="alert" className="mb-5 text-destructive">{error.message}</p>}
 {isLoading&&<p className="text-muted-foreground">Loading your agency…</p>}
 {data?.invitations.filter(i=>i.email.toLowerCase()===user?.email?.toLowerCase()).map(i=><div key={i.id} className="mb-4 flex flex-wrap items-center justify-between gap-3 border border-border p-4"><div><p className="font-medium">Invitation to {i.case_id?'a private case':'an agency circle'}</p><p className="text-sm text-muted-foreground">{i.role.replaceAll('_',' ')} · expires {formatDate(i.expires_at)}</p></div><Button disabled={mutation.isPending} onClick={()=>mutation.mutate({data:{action:'accept',invitationId:i.id}})}>Accept invitation</Button></div>)}
 {!agency?<section className="max-w-xl py-8"><Building2 className="h-9 w-9 text-primary"/><h2 className="mt-5 font-display text-3xl">Create your agency</h2><p className="mt-3 text-muted-foreground">Keep your clients and trusted professionals connected in your own private workspace.</p><form className="mt-7 space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate({data:{action:'create',name}})}}><Label htmlFor="agency-name">Agency name</Label><Input id="agency-name" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={160}/><Button disabled={mutation.isPending||name.trim().length<2}><Plus className="h-4 w-4"/>Create agency</Button></form><p className="mt-5 text-sm text-muted-foreground">Subscription plans are recorded as pilot requests. No automatic charge is made.</p></section>:<>
 <div className="mb-7 flex flex-wrap items-center justify-between gap-4"><Select value={agency.id} onValueChange={setAgencyId}><SelectTrigger className="w-64"><SelectValue/></SelectTrigger><SelectContent>{data?.agencies.map(a=><SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select>{admin&&<Button disabled={mutation.isPending} onClick={()=>mutation.mutate({data:{action:'case',agencyId:agency.id}})}><Plus className="h-4 w-4"/>Create case</Button>}</div>
 <div className="mb-8 grid grid-cols-2 gap-5 lg:grid-cols-4">{[['Active cases',scopedCases.filter(c=>c.status!=='closed').length],['Tasks needing action',data?.tasks.filter(t=>scopedCases.some(c=>c.id===t.case_id)&&t.status!=='complete').length??0],['Trusted team',scopedMembers.length],['Open incidents',data?.incidents.filter(i=>scopedCases.some(c=>c.id===i.case_id)&&i.status!=='resolved').length??0]].map(([l,v])=><div key={String(l)} className="border-l-2 border-primary pl-4"><p className="text-sm text-muted-foreground">{l}</p><p className="mt-2 font-display text-3xl">{v}</p></div>)}</div>
 <Tabs defaultValue="cases"><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="cases">Cases</TabsTrigger><TabsTrigger value="circle">Private circle & team</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger>{admin&&<TabsTrigger value="subscription">Subscription</TabsTrigger>}</TabsList>
 <TabsContent value="cases" className="mt-6">{scopedCases.length===0?<p className="py-8 text-muted-foreground">No cases yet.</p>:<div className="divide-y divide-border">{scopedCases.map(c=><Link key={c.id} to="/case-workspace" search={{case:c.id}} className="flex items-center justify-between gap-4 py-5"><div><p className="font-medium">{c.reference}</p><p className="mt-1 text-sm text-muted-foreground">{c.journey_stage} · opened {formatDate(c.created_at)}</p></div><ArrowRight className="h-4 w-4 text-primary"/></Link>)}</div>}</TabsContent>
 <TabsContent value="circle" className="mt-6"><div className="grid gap-8 lg:grid-cols-2"><section><h2 className="font-display text-2xl">Trusted professional circle & team</h2><p className="mt-2 text-sm text-muted-foreground">Case access is granted separately. Professional membership never opens every agency case.</p><ul className="mt-6 divide-y divide-border">{scopedMembers.map(m=><li key={m.id} className="flex items-center justify-between gap-3 py-4"><div><p className="text-sm font-medium">{m.user_id===user?.id?'You':`${m.role==='professional'?'Professional':'Team member'} · ${m.user_id.slice(0,8)}`}</p><Badge variant="secondary" className="mt-1">{m.role.replaceAll('_',' ')}</Badge><p className="mt-1 text-xs text-muted-foreground">{data?.credentials.filter(c=>c.user_id===m.user_id).map(c=>`${c.kind}: ${c.expires_at&&c.expires_at<new Date().toISOString().slice(0,10)?'expired':c.status}`).join(' · ')||'No credential review recorded'}</p></div>{admin&&m.user_id!==agency.owner_id&&<Button variant="ghost" size="icon" aria-label="Remove member access" onClick={()=>mutation.mutate({data:{action:'revoke',agencyId:agency.id,entityId:m.id,kind:'member'}})}><Trash2 className="h-4 w-4"/></Button>}</li>)}</ul></section>{admin&&<section><h2 className="font-display text-2xl">Invite your trusted team</h2><form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate({data:{action:'invite',agencyId:agency.id,email,role:inviteRole,permissions:['general','documents','appointments','messages']}})}}><Label htmlFor="invite-email">Email address</Label><Input id="invite-email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Select value={inviteRole} onValueChange={v=>setInviteRole(v as typeof inviteRole)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['professional','clinic_staff','agency_staff','agency_admin'].map(r=><SelectItem key={r} value={r}>{r.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select><Button disabled={mutation.isPending}><UserPlus className="h-4 w-4"/>Create invitation</Button></form><p className="mt-4 text-xs text-muted-foreground">Share the site address with your invitee. Their invitation appears after they sign in with this email. Email delivery is not enabled by this action.</p><ul className="mt-5 divide-y divide-border">{scopedInvites.map(i=><li key={i.id} className="flex items-center justify-between gap-2 py-3"><p className="break-all text-sm">{i.email}<span className="block text-xs text-muted-foreground">{i.role.replaceAll('_',' ')} · {i.case_id?'Case':'Circle'} invitation</span></p><Button size="icon" variant="ghost" aria-label="Revoke invitation" onClick={()=>mutation.mutate({data:{action:'revoke',agencyId:agency.id,entityId:i.id,kind:'invitation'}})}><Trash2 className="h-4 w-4"/></Button></li>)}</ul></section>}</div></TabsContent>
 <TabsContent value="activity" className="mt-6"><h2 className="font-display text-2xl">Timestamped activity</h2><ul className="mt-4 divide-y divide-border">{data?.audit.filter(a=>a.agency_id===agency.id).map(a=><li key={a.id} className="py-3 text-sm"><span className="font-medium">{a.action.replaceAll('_',' ')} · {a.entity.replaceAll('_',' ')}</span><span className="ml-3 text-muted-foreground">{formatDate(a.created_at)}</span></li>)}</ul></TabsContent>
 <TabsContent value="subscription" className="mt-6"><p className="text-sm text-muted-foreground">Current plan: {agency.plan}. Pilot records only; no automatic billing. White-label is a later Enterprise capability.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{AGENCY_PLANS.map(p=><article key={p.key} className="rounded-lg border border-border p-5"><h3 className="font-display text-xl">{p.name}</h3><p className="mt-3 text-lg">{p.key==='enterprise'?'From ':''}{formatMoney(p.amount)} / month</p><p className="my-4 text-sm text-muted-foreground">{p.cases}</p><Button size="sm" variant={agency.plan===p.key?'secondary':'outline'} disabled={mutation.isPending||agency.plan===p.key} onClick={()=>mutation.mutate({data:{action:'plan',agencyId:agency.id,plan:p.key}})}>{agency.plan===p.key?'Current plan':'Record plan request'}</Button></article>)}</div></TabsContent>
 </Tabs></>}
 </AppShell>
}