import {createFileRoute,Link} from '@tanstack/react-router';
import {useState} from 'react';
import {z} from 'zod';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {useServerFn} from '@tanstack/react-start';
import {toast} from 'sonner';
import {Plus,Check,UserPlus,Trash2} from 'lucide-react';
import {AppShell} from '@/components/AppShell';
import {CaseSelect} from '@/components/CaseSelect';
import {useCases,useMilestones} from '@/hooks/useCases';
import {useAuth} from '@/hooks/useAuth';
import {supabase} from '@/integrations/supabase/client';
import {agencyAction} from '@/lib/agency.functions';
import {pageHead} from '@/lib/site';
import {formatDate} from '@/lib/nestfam';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export const Route=createFileRoute('/case-workspace')({validateSearch:z.object({case:z.string().uuid().optional()}),head:()=>pageHead('Private case workspace','Coordinate participants, timeline, tasks, incidents and audit history inside your authorized case.'),component:CaseWorkspace});
function CaseWorkspace(){
 const search=Route.useSearch();const {user}=useAuth();const qc=useQueryClient();const {data:cases=[]}=useCases();const [caseId,setCaseId]=useState(search.case);const active=cases.find(c=>c.id===caseId)??cases[0];const {data:milestones=[]}=useMilestones(active?.id);const act=useServerFn(agencyAction);
 const [title,setTitle]=useState('');const [due,setDue]=useState('');const [assignee,setAssignee]=useState('');const [email,setEmail]=useState('');const [role,setRole]=useState<'intended_parent'|'carrier'|'professional'|'clinic_staff'|'case_manager'>('intended_parent');const [permissions,setPermissions]=useState(['general','documents','appointments','messages']);const [incidentTitle,setIncidentTitle]=useState('');const [detail,setDetail]=useState('');const [severity,setSeverity]=useState('medium');
 const {data:workspace,error}=useQuery({queryKey:['case-room',active?.id,user?.id],enabled:Boolean(active&&user),queryFn:async()=>{if(!active)throw new Error('Select a case');const [participants,tasks,incidents,audit,canWrite,canManage]=await Promise.all([supabase.from('case_participants').select('*').eq('case_id',active.id),supabase.from('case_tasks').select('*').eq('case_id',active.id).order('created_at'),supabase.from('incidents').select('*').eq('case_id',active.id).order('created_at',{ascending:false}),supabase.from('audit_logs').select('*').eq('case_id',active.id).order('created_at',{ascending:false}).limit(100),supabase.rpc('case_access',{_case:active.id,_domain:'general',_write:true}),active.agency_id?supabase.rpc('agency_access',{_agency:active.agency_id,_manage:true}):Promise.resolve({data:false,error:null})]);for(const r of [participants,tasks,incidents,audit,canWrite,canManage])if(r.error)throw new Error('Unable to load case information');return {participants:participants.data??[],tasks:tasks.data??[],incidents:incidents.data??[],audit:audit.data??[],canWrite:canWrite.data,canManage:canManage.data};}});
 const refresh=()=>{void qc.invalidateQueries();};
 const task=useMutation({mutationFn:async()=>{if(!active||!user)throw new Error('Sign in and select a case');const r=await supabase.from('case_tasks').insert({case_id:active.id,title:title.trim(),due_date:due||null,assigned_to:assignee||null,created_by:user.id});if(r.error)throw r.error;},onSuccess:()=>{setTitle('');refresh();toast.success('Task created');},onError:(e:Error)=>toast.error(e.message)});
 const updateTask=useMutation({mutationFn:async(input:{id:string;status:string})=>{const r=await supabase.from('case_tasks').update({status:input.status}).eq('id',input.id);if(r.error)throw r.error;},onSuccess:refresh,onError:(e:Error)=>toast.error(e.message)});
 const invite=useMutation({mutationFn:async()=>{if(!active?.agency_id)throw new Error('Agency case required');return act({data:{action:'invite',agencyId:active.agency_id,caseId:active.id,email,role,permissions:permissions as ('general'|'documents'|'appointments'|'messages'|'medical'|'legal'|'finance'|'incidents'|'audit')[]}});},onSuccess:()=>{setEmail('');refresh();toast.success('Invitation created. Share the site address with the recipient.');},onError:(e:Error)=>toast.error(e.message)});
 const incident=useMutation({mutationFn:async()=>{if(!active||!user)throw new Error('Select a case');const r=await supabase.from('incidents').insert({case_id:active.id,title:incidentTitle.trim(),detail:detail||null,severity,created_by:user.id});if(r.error)throw r.error;},onSuccess:()=>{setIncidentTitle('');setDetail('');refresh();toast.success('Concern recorded');},onError:(e:Error)=>toast.error(e.message)});
 const stage=useMutation({mutationFn:async(value:string)=>{if(!active)throw new Error('Select a case');const r=await supabase.from('cases').update({journey_stage:value,...(value==='Postpartum / Close-out'?{status:'closed' as const}:{})}).eq('id',active.id);if(r.error)throw r.error;},onSuccess:refresh,onError:(e:Error)=>toast.error(e.message)});
 return <AppShell title={active?`Case ${active.reference}`:'Private case workspace'} subtitle="What happens next. Who is responsible. Who has access."><div className="mb-6"><CaseSelect cases={cases} value={active?.id} onChange={setCaseId}/></div>{error&&<p role="alert" className="text-destructive">{error.message}</p>}{!active?<div className="py-10"><h2 className="font-display text-2xl">No assigned case yet</h2><p className="mt-3 text-muted-foreground">Your agency creates a case and invites your care team.</p><Button asChild className="mt-5"><Link to="/agency">Agency & invitations</Link></Button></div>:<Tabs defaultValue="overview"><TabsList className="flex h-auto flex-wrap justify-start">{['overview','participants','timeline','tasks','incidents','audit'].map(t=><TabsTrigger key={t} value={t} className="capitalize">{t}</TabsTrigger>)}</TabsList><TabsContent value="overview" className="mt-7"><p className="text-sm text-accent">CURRENT STAGE</p><h2 className="mt-3 font-display text-3xl">{active.journey_stage}</h2><p className="mt-3 text-sm text-muted-foreground">Opened {formatDate(active.created_at)} · Case manager {active.case_manager_id===user?.id?'You':active.case_manager_id?'Assigned':'Awaiting assignment'}</p>{workspace?.canWrite&&<Select value={active.journey_stage} onValueChange={v=>stage.mutate(v)}><SelectTrigger className="mt-5 w-72"><SelectValue/></SelectTrigger><SelectContent>{['Onboarding','Assessment','Legal','Matching','IVF / Treatment','Pregnancy','Birth','Postpartum / Close-out'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>}<div className="mt-8 grid gap-4 sm:grid-cols-3">{[{to:'/documents',title:'Documents'},{to:'/appointments',title:'Appointments'},{to:'/messages',title:'Messages'},{to:'/payments',title:'Financial plan'},{to:'/matches',title:'Assessment & matching'},{to:'/journey',title:'Clinical milestones'}].map(l=><Button key={l.to} asChild variant="outline"><Link to={l.to as '/documents'|'/appointments'|'/messages'|'/payments'|'/matches'|'/journey'}>{l.title}</Link></Button>)}</div><h3 className="mt-10 font-display text-xl">Next actions</h3>{workspace?.tasks.filter(t=>t.status!=='complete').slice(0,5).map(t=><p key={t.id} className="mt-3 border-t border-border pt-3 text-sm">{t.title} · {t.due_date?formatDate(t.due_date):'No due date'}</p>)}</TabsContent>
 <TabsContent value="participants" className="mt-7"><div className="grid gap-10 lg:grid-cols-2"><section><h2 className="font-display text-2xl">Authorized participants</h2><ul className="mt-5 divide-y divide-border">{workspace?.participants.filter(p=>p.active).map(p=><li key={p.id} className="flex items-center justify-between gap-3 py-4"><div><p className="text-sm font-medium">{p.user_id===user?.id?'You':p.user_id.slice(0,8)} · {p.role.replaceAll('_',' ')}</p><p className="mt-2 text-xs text-muted-foreground">{p.permissions.join(' · ')}</p></div>{workspace.canManage&&active.agency_id&&<Button size="icon" variant="ghost" aria-label="Remove participant access" onClick={async()=>{try{if(!active.agency_id)return;await act({data:{action:'revoke',agencyId:active.agency_id,entityId:p.id,kind:'participant'}});refresh();}catch(e){toast.error(e instanceof Error?e.message:'Unable to remove access');}}}><Trash2 className="h-4 w-4"/></Button>}</li>)}</ul></section>{workspace?.canManage&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();invite.mutate();}}><h2 className="font-display text-2xl">Invite a case participant</h2><Label htmlFor="participant-email">Email</Label><Input id="participant-email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Select value={role} onValueChange={v=>setRole(v as typeof role)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['intended_parent','carrier','professional','clinic_staff','case_manager'].map(r=><SelectItem key={r} value={r}>{r.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select><fieldset><legend className="mb-3 text-sm font-medium">Need-to-know permissions</legend><div className="grid grid-cols-2 gap-3">{['general','documents','appointments','messages','medical','legal','finance','incidents','audit'].map(p=><label key={p} className="flex items-center gap-2 text-sm capitalize"><Checkbox checked={permissions.includes(p)} onCheckedChange={v=>setPermissions(v?[...permissions,p]:permissions.filter(x=>x!==p))}/>{p}</label>)}</div></fieldset><Button disabled={invite.isPending}><UserPlus className="h-4 w-4"/>Create invitation</Button></form>}</div></TabsContent>
 <TabsContent value="timeline" className="mt-7"><ol className="space-y-4">{milestones.map((m,i)=><li key={m.id} className="flex gap-4 border-b border-border pb-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-secondary text-primary">{m.status==='complete'?<Check className="h-4 w-4"/>:i+1}</span><div><p className="font-medium">{m.label}</p><p className="text-sm text-muted-foreground">{m.status.replaceAll('_',' ')}{m.detail?` · ${m.detail}`:''}</p></div></li>)}</ol></TabsContent>
 <TabsContent value="tasks" className="mt-7"><div className="grid gap-10 lg:grid-cols-2"><section><h2 className="font-display text-2xl">Tasks & responsible people</h2><ul className="mt-5 divide-y divide-border">{workspace?.tasks.map(t=><li key={t.id} className="py-4"><p className="font-medium">{t.title}</p><p className="mt-1 text-xs text-muted-foreground">Due {formatDate(t.due_date)} · {t.assigned_to===user?.id?'Assigned to you':t.assigned_to?t.assigned_to.slice(0,8):'Unassigned'}</p>{(workspace.canWrite||t.assigned_to===user?.id)?<Select value={t.status} onValueChange={v=>updateTask.mutate({id:t.id,status:v})}><SelectTrigger className="mt-3 w-44"><SelectValue/></SelectTrigger><SelectContent>{['pending','in_progress','complete','blocked'].map(s=><SelectItem key={s} value={s}>{s.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select>:<Badge variant="secondary" className="mt-2">{t.status}</Badge>}</li>)}</ul></section>{workspace?.canWrite&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();task.mutate();}}><h2 className="font-display text-2xl">Create task</h2><Label htmlFor="task-title">Task</Label><Input id="task-title" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={240}/><Label htmlFor="task-due">Due date</Label><Input id="task-due" type="date" value={due} onChange={e=>setDue(e.target.value)}/><Select value={assignee||'unassigned'} onValueChange={v=>setAssignee(v==='unassigned'?'':v)}><SelectTrigger><SelectValue placeholder="Responsible person"/></SelectTrigger><SelectContent><SelectItem value="unassigned">Unassigned</SelectItem><SelectItem value={user?.id||'me'}>You</SelectItem>{workspace.participants.filter(p=>p.active&&p.user_id!==user?.id).map(p=><SelectItem key={p.id} value={p.user_id}>{p.role.replaceAll('_',' ')} · {p.user_id.slice(0,8)}</SelectItem>)}</SelectContent></Select><Button disabled={task.isPending}><Plus className="h-4 w-4"/>Create task</Button></form>}</div></TabsContent>
 <TabsContent value="incidents" className="mt-7"><div className="grid gap-10 lg:grid-cols-2"><section><h2 className="font-display text-2xl">Concerns & escalations</h2>{workspace?.incidents.map(i=><article key={i.id} className="mt-5 border-t border-border pt-5"><div className="flex justify-between gap-3"><h3>{i.title}</h3><Badge variant={i.severity==='critical'?'destructive':'secondary'}>{i.severity} · {i.status}</Badge></div><p className="mt-3 text-sm text-muted-foreground">{i.detail}</p>{i.resolution&&<p className="mt-2 text-sm">Resolution: {i.resolution}</p>}{workspace.canWrite&&i.status!=='resolved'&&<div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={async()=>{const r=await supabase.from('incidents').update({status:'escalated',responder_id:user?.id??null}).eq('id',i.id);if(r.error)toast.error(r.error.message);else refresh();}}>Escalate</Button><Button size="sm" variant="outline" onClick={async()=>{const resolution=window.prompt('Record resolution and actions taken');if(!resolution?.trim())return;const r=await supabase.from('incidents').update({status:'resolved',resolution,responder_id:user?.id??null,resolved_at:new Date().toISOString()}).eq('id',i.id);if(r.error)toast.error(r.error.message);else refresh();}}>Resolve</Button></div>}</article>)}</section><form className="space-y-4" onSubmit={e=>{e.preventDefault();incident.mutate();}}><h2 className="font-display text-2xl">Report a concern</h2><p className="text-sm text-muted-foreground">For urgent medical issues, contact your clinician or emergency services first.</p><Label htmlFor="incident-title">Concern</Label><Input id="incident-title" value={incidentTitle} onChange={e=>setIncidentTitle(e.target.value)} required maxLength={240}/><Label htmlFor="incident-detail">Details</Label><Textarea id="incident-detail" value={detail} onChange={e=>setDetail(e.target.value)}/><Select value={severity} onValueChange={setSeverity}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['low','medium','high','critical'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Button disabled={incident.isPending}>Record concern</Button></form></div></TabsContent>
 <TabsContent value="audit" className="mt-7"><h2 className="font-display text-2xl">Timestamped case history</h2><p className="mt-2 text-sm text-muted-foreground">Visible only with audit access.</p><ul className="mt-5 divide-y divide-border">{workspace?.audit.map(a=><li key={a.id} className="py-3 text-sm">{a.action} · {a.entity.replaceAll('_',' ')}<span className="ml-3 text-muted-foreground">{new Date(a.created_at).toLocaleString('en-GB')}</span></li>)}</ul></TabsContent></Tabs>}</AppShell>
}