CREATE TABLE public.agencies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK(length(name) BETWEEN 2 AND 160), owner_id uuid NOT NULL REFERENCES public.profiles(id), plan text NOT NULL DEFAULT 'starter' CHECK(plan IN ('starter','professional','growth','enterprise')), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.agencies TO authenticated; GRANT ALL ON public.agencies TO service_role;
ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.agency_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), agency_id uuid NOT NULL REFERENCES public.agencies(id), user_id uuid NOT NULL REFERENCES public.profiles(id), role text NOT NULL CHECK(role IN ('agency_admin','agency_staff','professional','clinic_staff')), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(agency_id,user_id));
GRANT SELECT ON public.agency_members TO authenticated; GRANT ALL ON public.agency_members TO service_role;
ALTER TABLE public.agency_members ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.case_participants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES public.cases(id), user_id uuid NOT NULL REFERENCES public.profiles(id), role text NOT NULL CHECK(role IN ('intended_parent','carrier','professional','clinic_staff','case_manager')), permissions text[] NOT NULL DEFAULT ARRAY['general','documents','appointments','messages'], active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(case_id,user_id));
GRANT SELECT ON public.case_participants TO authenticated; GRANT ALL ON public.case_participants TO service_role;
ALTER TABLE public.case_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases ADD COLUMN agency_id uuid REFERENCES public.agencies(id), ADD COLUMN journey_stage text NOT NULL DEFAULT 'Onboarding', ADD COLUMN case_manager_id uuid REFERENCES public.profiles(id);
ALTER TABLE public.matches ADD COLUMN agency_id uuid REFERENCES public.agencies(id), ADD COLUMN case_id uuid REFERENCES public.cases(id), ADD COLUMN assessment_status text NOT NULL DEFAULT 'pending', ADD COLUMN professional_decision text;
CREATE TABLE public.agency_invitations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), agency_id uuid NOT NULL REFERENCES public.agencies(id), case_id uuid REFERENCES public.cases(id), email text NOT NULL CHECK(length(email)<255), role text NOT NULL CHECK(role IN ('agency_admin','agency_staff','professional','clinic_staff','intended_parent','carrier','case_manager')), permissions text[] NOT NULL DEFAULT ARRAY['general','documents','appointments','messages'], invited_by uuid NOT NULL REFERENCES public.profiles(id), status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','revoked')), expires_at timestamptz NOT NULL DEFAULT now()+interval '7 days', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.agency_invitations TO authenticated; GRANT ALL ON public.agency_invitations TO service_role;
ALTER TABLE public.agency_invitations ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.agency_access(_agency uuid, _manage boolean DEFAULT false) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.agency_members WHERE agency_id=_agency AND user_id=auth.uid() AND active AND (NOT _manage OR role='agency_admin')) AND NOT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND suspended) $$;
REVOKE ALL ON FUNCTION public.agency_access(uuid,boolean) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.agency_access(uuid,boolean) TO authenticated,service_role;
CREATE OR REPLACE FUNCTION public.case_access(_case uuid,_domain text DEFAULT 'general',_write boolean DEFAULT false) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT auth.uid() IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND suspended) AND EXISTS(SELECT 1 FROM public.cases c WHERE c.id=_case AND (CASE WHEN c.agency_id IS NULL THEN (auth.uid() IN (c.parent_id,c.surrogate_id,c.clinic_id,c.lawyer_id,c.counselor_id) AND (NOT _write OR _domain IN ('messages','documents','appointments') OR auth.uid() IN(c.clinic_id,c.lawyer_id,c.counselor_id))) ELSE (EXISTS(SELECT 1 FROM public.agency_members m WHERE m.agency_id=c.agency_id AND m.user_id=auth.uid() AND m.active AND m.role IN('agency_admin','agency_staff')) OR EXISTS(SELECT 1 FROM public.case_participants p WHERE p.case_id=c.id AND p.user_id=auth.uid() AND p.active AND _domain=ANY(p.permissions) AND (NOT _write OR p.role IN('case_manager','professional','clinic_staff') OR _domain IN('messages','documents','appointments','incidents')))) END)) $$;
REVOKE ALL ON FUNCTION public.case_access(uuid,text,boolean) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.case_access(uuid,text,boolean) TO authenticated,service_role;
CREATE OR REPLACE FUNCTION public.is_case_member(_case_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.case_access(_case_id,'general',false) $$;
CREATE POLICY agencies_read ON public.agencies FOR SELECT TO authenticated USING(public.agency_access(id) OR owner_id=auth.uid() OR public.is_admin());
CREATE POLICY agency_members_read ON public.agency_members FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.agency_access(agency_id) OR public.is_admin());
CREATE POLICY participants_read ON public.case_participants FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.case_access(case_id));
CREATE POLICY invitations_read ON public.agency_invitations FOR SELECT TO authenticated USING(public.agency_access(agency_id,true) OR lower(email)=lower(auth.jwt()->>'email'));
CREATE TABLE public.case_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES public.cases(id), title text NOT NULL CHECK(length(title) BETWEEN 1 AND 240), assigned_to uuid REFERENCES public.profiles(id), due_date date, status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','in_progress','complete','blocked')), created_by uuid NOT NULL REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.case_tasks TO authenticated; GRANT ALL ON public.case_tasks TO service_role;
ALTER TABLE public.case_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY tasks_read ON public.case_tasks FOR SELECT TO authenticated USING(public.case_access(case_id));
CREATE POLICY tasks_insert ON public.case_tasks FOR INSERT TO authenticated WITH CHECK(public.case_access(case_id,'general',true) AND created_by=auth.uid());
CREATE POLICY tasks_update ON public.case_tasks FOR UPDATE TO authenticated USING(public.case_access(case_id,'general',true) OR assigned_to=auth.uid()) WITH CHECK(public.case_access(case_id));
CREATE TABLE public.incidents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES public.cases(id), title text NOT NULL CHECK(length(title) BETWEEN 1 AND 240), detail text, severity text NOT NULL DEFAULT 'medium' CHECK(severity IN('low','medium','high','critical')), status text NOT NULL DEFAULT 'open' CHECK(status IN('open','escalated','resolved')), responder_id uuid REFERENCES public.profiles(id), resolution text, created_by uuid NOT NULL REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz);
GRANT SELECT,INSERT,UPDATE ON public.incidents TO authenticated; GRANT ALL ON public.incidents TO service_role;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
CREATE POLICY incidents_read ON public.incidents FOR SELECT TO authenticated USING(created_by=auth.uid() OR public.case_access(case_id,'incidents') OR public.is_admin());
CREATE POLICY incidents_insert ON public.incidents FOR INSERT TO authenticated WITH CHECK(created_by=auth.uid() AND public.case_access(case_id));
CREATE POLICY incidents_update ON public.incidents FOR UPDATE TO authenticated USING(public.case_access(case_id,'incidents',true)) WITH CHECK(public.case_access(case_id,'incidents',true));
CREATE TABLE public.financial_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),case_id uuid NOT NULL REFERENCES public.cases(id),category text NOT NULL CHECK(category IN('clinic','professional','agency','carrier','nestfam','contingency')),label text NOT NULL,amount numeric NOT NULL CHECK(amount>=0),status text NOT NULL DEFAULT 'planned' CHECK(status IN('planned','due','paid','cancelled')),due_date date,external_reference text,created_by uuid NOT NULL REFERENCES public.profiles(id),created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.financial_items TO authenticated; GRANT ALL ON public.financial_items TO service_role;
ALTER TABLE public.financial_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY finance_read ON public.financial_items FOR SELECT TO authenticated USING(public.case_access(case_id,'finance'));
CREATE POLICY finance_insert ON public.financial_items FOR INSERT TO authenticated WITH CHECK(public.case_access(case_id,'finance',true) AND created_by=auth.uid());
CREATE POLICY finance_update ON public.financial_items FOR UPDATE TO authenticated USING(public.case_access(case_id,'finance',true)) WITH CHECK(public.case_access(case_id,'finance',true));
CREATE TABLE public.subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),agency_id uuid NOT NULL UNIQUE REFERENCES public.agencies(id),plan text NOT NULL DEFAULT 'starter',monthly_amount numeric NOT NULL DEFAULT 75000,status text NOT NULL DEFAULT 'pilot' CHECK(status IN('pilot','active','paused','cancelled')),created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.subscriptions TO authenticated; GRANT ALL ON public.subscriptions TO service_role;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY subscriptions_read ON public.subscriptions FOR SELECT TO authenticated USING(public.agency_access(agency_id,true) OR public.is_admin());
CREATE TABLE public.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),agency_id uuid REFERENCES public.agencies(id),case_id uuid REFERENCES public.cases(id),actor_id uuid,action text NOT NULL,entity text NOT NULL,entity_id uuid,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.audit_logs TO authenticated; GRANT ALL ON public.audit_logs TO service_role;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_read ON public.audit_logs FOR SELECT TO authenticated USING(public.agency_access(agency_id,true) OR public.case_access(case_id,'audit') OR public.is_admin());
CREATE TABLE public.professional_credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES public.profiles(id),kind text NOT NULL,reference text,expires_at date,status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','verified','suspended','expired')),verification_scope text,created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.professional_credentials TO authenticated; GRANT ALL ON public.professional_credentials TO service_role;
ALTER TABLE public.professional_credentials ENABLE ROW LEVEL SECURITY;
CREATE POLICY credentials_read ON public.professional_credentials FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_admin() OR EXISTS(SELECT 1 FROM public.agency_members m WHERE m.user_id=professional_credentials.user_id AND public.agency_access(m.agency_id,true)));
CREATE POLICY credentials_insert ON public.professional_credentials FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid() AND status='pending' AND verification_scope IS NULL);
CREATE TABLE public.consents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES public.profiles(id),case_id uuid REFERENCES public.cases(id),kind text NOT NULL,version text NOT NULL DEFAULT '2026-10',created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.consents TO authenticated; GRANT ALL ON public.consents TO service_role;
ALTER TABLE public.consents ENABLE ROW LEVEL SECURITY;
CREATE POLICY consents_read ON public.consents FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.case_access(case_id,'audit'));
CREATE POLICY consents_insert ON public.consents FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid() AND (case_id IS NULL OR public.case_access(case_id)));
CREATE TABLE public.support_tickets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES public.profiles(id),subject text NOT NULL,body text NOT NULL,status text NOT NULL DEFAULT 'open',created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.support_tickets TO authenticated; GRANT ALL ON public.support_tickets TO service_role;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY support_read ON public.support_tickets FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_admin());
CREATE POLICY support_insert ON public.support_tickets FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid() AND status='open');
ALTER TABLE public.documents ADD COLUMN storage_path text, ADD COLUMN expires_at date, ADD COLUMN version integer NOT NULL DEFAULT 1, ADD COLUMN previous_version_id uuid REFERENCES public.documents(id), ADD COLUMN visibility_domain text NOT NULL DEFAULT 'documents' CHECK(visibility_domain IN('documents','medical','legal','finance'));
ALTER TABLE public.verifications ADD COLUMN expires_at date, ADD COLUMN verification_scope text, ADD COLUMN storage_path text;
CREATE OR REPLACE FUNCTION public.log_case_change() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE cid uuid; aid uuid; BEGIN IF TG_TABLE_NAME='cases' THEN cid=NEW.id; aid=NEW.agency_id; ELSE cid=NEW.case_id; SELECT agency_id INTO aid FROM public.cases WHERE id=cid; END IF; INSERT INTO public.audit_logs(agency_id,case_id,actor_id,action,entity,entity_id) VALUES(aid,cid,auth.uid(),TG_OP,TG_TABLE_NAME,NEW.id); RETURN NEW; END $$;
REVOKE ALL ON FUNCTION public.log_case_change() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER agency_case_audit AFTER INSERT OR UPDATE ON public.cases FOR EACH ROW EXECUTE FUNCTION public.log_case_change();
CREATE TRIGGER task_audit AFTER INSERT OR UPDATE ON public.case_tasks FOR EACH ROW EXECUTE FUNCTION public.log_case_change();
CREATE TRIGGER incident_audit AFTER INSERT OR UPDATE ON public.incidents FOR EACH ROW EXECUTE FUNCTION public.log_case_change();
CREATE TRIGGER finance_audit AFTER INSERT OR UPDATE ON public.financial_items FOR EACH ROW EXECUTE FUNCTION public.log_case_change();
CREATE TRIGGER document_audit AFTER INSERT OR UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION public.log_case_change();
CREATE INDEX agency_members_user_idx ON public.agency_members(user_id,agency_id);
CREATE INDEX case_participants_user_idx ON public.case_participants(user_id,case_id);
CREATE INDEX cases_agency_idx ON public.cases(agency_id);
COMMENT ON TABLE public.escrow_accounts IS 'DEPRECATED: historical custody-model records; V1 uses non-custodial financial_items.';
COMMENT ON TABLE public.escrow_transactions IS 'DEPRECATED: historical records; no active NestFam custody workflow.';
COMMENT ON COLUMN public.matches.score IS 'DEPRECATED: automated ranking is not used by agency-led professional matching.';