/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ForAgenciesRouteImport } from './routes/for-agencies'
import { Route as ForCarriersRouteImport } from './routes/for-carriers'
import { Route as ForIntendedParentsRouteImport } from './routes/for-intended-parents'
import { Route as ForProfessionalsRouteImport } from './routes/for-professionals'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SafetyTrustRouteImport } from './routes/safety-trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationRouteImport } from './routes/verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgenciesRoute = ForAgenciesRouteImport.update({
  id: '/for-agencies',
  path: '/for-agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCarriersRoute = ForCarriersRouteImport.update({
  id: '/for-carriers',
  path: '/for-carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForIntendedParentsRoute = ForIntendedParentsRouteImport.update({
  id: '/for-intended-parents',
  path: '/for-intended-parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProfessionalsRoute = ForProfessionalsRouteImport.update({
  id: '/for-professionals',
  path: '/for-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyTrustRoute = SafetyTrustRouteImport.update({
  id: '/safety-trust',
  path: '/safety-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agency': typeof AgencyRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/for-carriers': typeof ForCarriersRoute
  '/for-intended-parents': typeof ForIntendedParentsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journey': typeof JourneyRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/safety-trust': typeof SafetyTrustRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agency': typeof AgencyRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/for-carriers': typeof ForCarriersRoute
  '/for-intended-parents': typeof ForIntendedParentsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journey': typeof JourneyRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/safety-trust': typeof SafetyTrustRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agency': typeof AgencyRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/for-carriers': typeof ForCarriersRoute
  '/for-intended-parents': typeof ForIntendedParentsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journey': typeof JourneyRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/safety-trust': typeof SafetyTrustRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agency'
    | '/appointments'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/documents'
    | '/for-agencies'
    | '/for-carriers'
    | '/for-intended-parents'
    | '/for-professionals'
    | '/how-it-works'
    | '/journey'
    | '/matches'
    | '/messages'
    | '/payments'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/safety-trust'
    | '/terms'
    | '/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agency'
    | '/appointments'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/documents'
    | '/for-agencies'
    | '/for-carriers'
    | '/for-intended-parents'
    | '/for-professionals'
    | '/how-it-works'
    | '/journey'
    | '/matches'
    | '/messages'
    | '/payments'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/safety-trust'
    | '/terms'
    | '/verification'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agency'
    | '/appointments'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/documents'
    | '/for-agencies'
    | '/for-carriers'
    | '/for-intended-parents'
    | '/for-professionals'
    | '/how-it-works'
    | '/journey'
    | '/matches'
    | '/messages'
    | '/payments'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/safety-trust'
    | '/terms'
    | '/verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgencyRoute: typeof AgencyRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ForAgenciesRoute: typeof ForAgenciesRoute
  ForCarriersRoute: typeof ForCarriersRoute
  ForIntendedParentsRoute: typeof ForIntendedParentsRoute
  ForProfessionalsRoute: typeof ForProfessionalsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JourneyRoute: typeof JourneyRoute
  MatchesRoute: typeof MatchesRoute
  MessagesRoute: typeof MessagesRoute
  PaymentsRoute: typeof PaymentsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SafetyTrustRoute: typeof SafetyTrustRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agencies': {
      id: '/for-agencies'
      path: '/for-agencies'
      fullPath: '/for-agencies'
      preLoaderRoute: typeof ForAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-carriers': {
      id: '/for-carriers'
      path: '/for-carriers'
      fullPath: '/for-carriers'
      preLoaderRoute: typeof ForCarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-intended-parents': {
      id: '/for-intended-parents'
      path: '/for-intended-parents'
      fullPath: '/for-intended-parents'
      preLoaderRoute: typeof ForIntendedParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-professionals': {
      id: '/for-professionals'
      path: '/for-professionals'
      fullPath: '/for-professionals'
      preLoaderRoute: typeof ForProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-trust': {
      id: '/safety-trust'
      path: '/safety-trust'
      fullPath: '/safety-trust'
      preLoaderRoute: typeof SafetyTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgencyRoute: AgencyRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ForAgenciesRoute: ForAgenciesRoute,
  ForCarriersRoute: ForCarriersRoute,
  ForIntendedParentsRoute: ForIntendedParentsRoute,
  ForProfessionalsRoute: ForProfessionalsRoute,
  HowItWorksRoute: HowItWorksRoute,
  JourneyRoute: JourneyRoute,
  MatchesRoute: MatchesRoute,
  MessagesRoute: MessagesRoute,
  PaymentsRoute: PaymentsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SafetyTrustRoute: SafetyTrustRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
